version: '3.8'

services:
  # Base de datos para Clínicas
  db-clinicas:
    image: postgres:15
    container_name: postgres_clinicas
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: clinicas
    ports:
      - "5436:5432"
    volumes:
      - pg_data_clinicas:/var/lib/postgresql/data

  # Base de datos para Doctores
  db-doctores:
    image: postgres:15
    container_name: postgres_doctores
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: doctores
    ports:
      - "5433:5432"
    volumes:
      - pg_data_doctores:/var/lib/postgresql/data

  # Base de datos para Pacientes
  db-pacientes:
    image: postgres:15
    container_name: postgres_pacientes
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pacientes
    ports:
      - "5434:5432"
    volumes:
      - pg_data_pacientes:/var/lib/postgresql/data

  # Base de datos para Medicamentos
  db-medicamentos:
    image: postgres:15
    container_name: postgres_medicamentos
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: medicamentos
    ports:
      - "5435:5432"
    volumes:
      - pg_data_medicamentos:/var/lib/postgresql/data

  # Microservicio Clínicas
  ms-clinicas:
    build:
      context: ./ms-clinicas
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: ms-clinicas
    restart: always
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db-clinicas:5432/clinicas
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - db-clinicas

  # Microservicio Doctores
  ms-doctores:
    build:
      context: ./ms-doctores
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: ms-doctores
    restart: always
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db-doctores:5432/doctores
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: admin
    ports:
      - "8081:8080"
    depends_on:
      - db-doctores

  # Microservicio Pacientes
  ms-pacientes:
    build:
      context: ./ms-pacientes
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: ms-pacientes
    restart: always
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db-pacientes:5432/pacientes
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: admin
    ports:
      - "8082:8080"
    depends_on:
      - db-pacientes

  # Microservicio Medicamentos
  ms-medicamentos:
    build:
      context: ./ms-medicamentos
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: ms-medicamentos
    restart: always
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db-medicamentos:5432/medicamentos
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: admin
    ports:
      - "8083:8080"
    depends_on:
      - db-medicamentos

volumes:
  pg_data_clinicas:
  pg_data_doctores:
  pg_data_pacientes:
  pg_data_medicamentos:
